global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']

  - job_name: 'market-data'
    static_configs:
      - targets: ['market-data:8001']

  - job_name: 'order-management'
    static_configs:
      - targets: ['order-management:8002']

  - job_name: 'trade-execution'
    static_configs:
      - targets: ['trade-execution:8003']

  - job_name: 'ai-signal'
    static_configs:
      - targets: ['ai-signal:8004']
